# 调试模式
debug: false

# 崩溃玩家客户端设置
crashSettings:
  # 开关
  enable: true
  # 默认崩溃模式
  # (explosion changeHoldItem posAndLook invalidParticle)
  defaultType: "explosion"
  # 命令
  commands:
    - "crash"

knockBackSettings:
  #开关
  enable: true
  #击退的设置
  vector:
    x: 0.75
    y: 0.5
    z: 0.75
  # 命令
  commands:
    - "kb"
    - "knockback"

# 查看在线列表
listSettings:
  # 开关
  enable: true
  # 命令
  commands:
    - "list"