# 调试模式
debug: false

# 数据库设置
databaseSettings:
  # 数据库类型
  # (mysql h2)
  type: "h2"
  # MySQL数据库设置
  mysql:
    # 地址
    host: "127.0.0.1:3306"
    # 数据库
    database: "mhdf_tools"
    # 用户
    user: "root"
    # 密码
    password: "root"
  # H2数据库设置
  h2:
    # 数据库文件
    file: "database.db"

# 缓存设置
cacheSettings:
  # 存储类型
  # (map redis)
  type: "map"
  # Redis数据库设置
  redis:
    # 地址
    host: "localhost:6379"
    # 用户
    user: ""
    # 密码
    password: ""

# 崩溃玩家客户端
crashSettings:
  # 开关
  enable: true
  # 默认崩溃模式
  # (explosion changeHoldItem posAndLook invalidParticle)
  defaultType: "explosion"
  # 命令
  commands:
    - "crash"

# 击退玩家
knockBackSettings:
  #开关
  enable: true
  #击退的设置
  vector:
    x: 0.75
    y: 0.5
    z: 0.75
  # 命令
  commands:
    - "kb"
    - "knockback"

# 查看在线列表
listSettings:
  # 开关
  enable: true
  # 命令
  commands:
    - "list"

# 飞行
flySettings:
  # 开关
  enable: true
  # 自动开启
  autoEnable:
    # 加入服务器
    joinServer: true
    # 切换世界
    changeWorld: true
    # 重生
    respawn: true
  # 自动关闭
  autoDisable:
    # 掉血
    takeHealth: false
    # 世界列表
    worldList:
      - "awa"
  # 飞行强制关闭坠落倒计时
  fallTime: 5
  # 命令
  commands:
    - "fly"
  # 限时飞行命令
  flyTimeCommands:
    - "flytime"

# 隐身
vanishSettings:
  # 开关
  enable: true
  # 从补全中移除
  tabRemove: true
  # 命令
  commands:
    - "vanish"

# 更好的关服
stopSettings:
  # 开关
  enable: true
  # 关闭服务器的时候保存存档
  autoSave: true
  # 默认倒计时(-1关闭)
  defaultCountdown: 5
  # 命令
  commands:
    - "stop"

# 快速使用
fastUseSettings:
  # 开关
  enable: true
  # 潜影盒(权限: mhdftools.fastuse.shulkerbox)
  shulkerBox: true
  # 末影箱(权限: mhdftools.fastuse.enderchest)
  enderChest: true
  # 工作台(权限: mhdftools.fastuse.craftingtable)
  craftingTable: true

# 进服消息
joinMessageSettings:
  # 开关
  enable: true
  # 默认
  default:
    # 权重
    weight: 0
    # 提示消息
    message: "&a[+] &e{player}"
  # 拥有 mhdftools.group.joinmessage.<名字> 权限的提示
  # 例如 mhdftools.group.joinmessage.admin
  admin:
    # 权重
    weight: 1
    # 提示消息
    message: "&a[+] &c{player}"

# 退服消息
quitMessageSettings:
  # 开关
  enable: true
  # 默认
  default:
    # 权重
    weight: 0
    # 提示消息
    message: "&c[-] &e{player}"
  # 拥有 mhdftools.group.quitmessage.<名字> 权限的提示
  # 例如 mhdftools.group.quitmessage.admin
  admin:
    # 权重
    weight: 1
    # 提示消息
    message: "&c[-] &c{player}"