name: MHDF-Tools
version: '${project.version}'
main: cn.chengzhiya.mhdftools.Main
api-version: '1.20'
folia-supported: true
authoendrs: [ BaiShenYao_Dog, Dg32z_, Araykal ]
softdepend: [ Vault, PlaceholderAPI, MythicMobs, CraftEngine ]