name: Cheng-Tools-Reloaded
version: '${project.version}'
main: cn.ChengZhiYa.ChengToolsReloaded.main
api-version: 1.18
authors: [ ChengZhiYa ]
description: qwq
permissions:
  ChengTools.Op:
    default: op
  ChengTools.Gamemode:
    default: op
  ChengTools.Fly:
    default: op
  ChengTools.Fly.Give:
    default: op
  ChengTools.Vanish:
    default: op
  ChengTools.Vanish.Give:
    default: op
  ChengTools.Chat:
    default: true
  ChengTools.Chat.DelayBypass:
    default: op
  ChengTools.Chat.BlackWorkBypass:
    default: op
  ChengTools.Chat.Color:
    default: op
  ChengTools.Day:
    default: op
  ChengTools.Night:
    default: op
  ChengTools.Sun:
    default: op
  ChengTools.Reload:
    default: op
  ChengTools.PluginManage:
    default: op
  ChengTools.PlayerTitle:
    default: op
  ChengTools.Stop:
    default: op
  ChengTools.Crash:
    default: op
  ChengTools.Freeze:
    default: op
  ChengTools.Ip:
    default: op
  ChengTools.SetSpawn:
    default: op
  ChengTools.Point:
    default: op