name: Cheng-Tools-Reloaded
version: '${project.version}'
main: cn.ChengZhiYa.ChengToolsReloaded.ChengToolsReloaded
api-version: 1.16
authors: [ ChengZhiYa ]
softdepend: [ Vault, PlaceholderAPI, ProtocolLib ]
description: qwq
permissions:
  ChengTools.Command.Gamemode:
    default: op
  ChengTools.Command.Fly:
    default: op
  ChengTools.Command.Fly.Give:
    default: op
  ChengTools.Command.Vanish:
    default: op
  ChengTools.Command.Vanish.Give:
    default: op
  ChengTools.Command.Day:
    default: op
  ChengTools.Command.Night:
    default: op
  ChengTools.Command.Sun:
    default: op
  ChengTools.Command.Invsee:
    default: op
  ChengTools.Command.Reload:
    default: op
  ChengTools.Command.PluginManage:
    default: op
  ChengTools.Command.PlayerTitle:
    default: op
  ChengTools.Command.Stop:
    default: op
  ChengTools.Command.Crash:
    default: op
  ChengTools.Command.Freeze:
    default: op
  ChengTools.Command.Ip:
    default: op
  ChengTools.Command.SetSpawn:
    default: op
  ChengTools.Command.Point:
    default: op
  ChengTools.Command.MoneyAdmin:
    default: op
  ChengTools.SendUpdateMessage:
    default: op
  ChengTools.Home:
    default: true
  ChengTools.Chat:
    default: true
  ChengTools.Chat.DelayBypass:
    default: op
  ChengTools.Chat.BlackWorkBypass:
    default: op
  ChengTools.Chat.Color:
    default: op
  ChengTools.JoinMessage:
    default: true
  ChengTools.QuitMessage:
    default: true