name: MHDF-Tools
version: '${project.version}'
main: cn.ChengZhiYa.MHDFTools.MHDFTools
api-version: '1.20'
authoendrs: [ ChengZhiYa ]
softdepend: [ Vault, PlaceholderAPI, ProtocolLib ]
description: qwq
permissions:
  MHDFTools.Admin:
    default: op
  MHDFTools.Command.Gamemode:
    default: op
  MHDFTools.Command.Fly:
    default: op
  MHDFTools.Command.Fly.Give:
    default: op
  MHDFTools.Command.Vanish:
    default: op
  MHDFTools.Command.Vanish.Give:
    default: op
  MHDFTools.Command.Day:
    default: op
  MHDFTools.Command.Night:
    default: op
  MHDFTools.Command.Sun:
    default: op
  MHDFTools.Command.Invsee:
    default: op
  MHDFTools.Command.PlayerTitle:
    default: op
  MHDFTools.Command.Stop:
    default: op
  MHDFTools.Command.Crash:
    default: op
  MHDFTools.Command.Freeze:
    default: op
  MHDFTools.Command.Ip:
    default: op
  MHDFTools.Command.SetSpawn:
    default: op
  MHDFTools.Command.Point:
    default: op
  MHDFTools.Command.MoneyAdmin:
    default: op
  MHDFTools.SendUpdateMessage:
    default: op
  MHDFTools.Home:
    default: true
  MHDFTools.Chat:
    default: true
  MHDFTools.Chat.DelayBypass:
    default: op
  MHDFTools.Chat.BlackWorkBypass:
    default: op
  MHDFTools.Chat.Color:
    default: op
  MHDFTools.JoinMessage:
    default: true
  MHDFTools.QuitMessage:
    default: true
libraries:
  - 'com.alibaba:fastjson:1.2.83'
  - 'com.zaxxer:HikariCP:5.0.1'
  - 'org.apache.httpcomponents:httpclient:4.5.13'