#自定义玩家进入服务器提示
CustomJoinServerMessageSettings:
  #开关
  Enable: true
  #玩家进入服务器的提示
  PlayerJoinMessage: "&7[&8玩家&7]&a&l%PlayerName%&e&l加入了游戏"
  #管理员进入服务器的提示
  AdminJoinMessage: "&7[&c管理员&7]&a&l%PlayerName%&e&l加入了游戏"

#自定义玩家退出服务器提示
CustomQuitServerMessageSettings:
  #开关
  Enable: true
  #玩家退出服务器的提示
  PlayerQuitMessage: "&7[&8&l玩家&7]&a&l%PlayerName%&e&l离开了游戏"
  #管理员退出服务器的提示
  AdminQuitMessage: "&7[&c&l管理员&7]&a&l%PlayerName%&e&l离开了游戏"

#更简单的Gamemode
EasyGamemodeCommandEnable: true

#Fly系统
FlyEnable: true

#Vanish系统
VanishEnable: true

#Back系统
BackEnable: true

#崩端系统
CrashPlayerEnable: true

#插件管理系统:
PluginManageEnable: true

#快速晴天命令:
FastSunCommandEnable: true

#快速调时间命令:
FastSetTimeCommandEnable: true

#超级List设置
SuperListSettings:
  #开关
  Enable: true
  #命令提示
  Message:
    - "&7-----------&6List系统&7-----------"
    - "&eTPS: %TPS_1% %TPS_5% %TPS_15%"
    - "&e内存占用: %mem_used%&7/&e%mem_max%"
    - "&e在线玩家: %Online%/%Max_Online%"
    - "&e玩家列表:"
    - "&e%PlayerList%"
    - "&7-----------&6List系统&7-----------"

#家系统
HomeSystemSettings:
  #开关
  Enable: true
  #一个玩家最多能创建多少个家
  MaxHomeTime: 5

#Tpa系统设置
TpaSettings:
  #开关
  Enable: true
  #默认提示模式 1:聊天栏模式 2:菜单模式
  DefaultMode: 1

#公告系统
TimeMessageSettings:
  #开关
  Enable: true
  #公告延时(单位:秒)
  Delay: 60
  #公告内容
  Message:
    - "欢迎使用橙汁插件!"

#登录系统功能
LoginSystemSettings:
  #开关
  Enable: true
  #密码最短长度限制
  MinPaswordLength: 6
  #密码最大长度限制
  MaxPaswordLength: 18
  #过于简单的密码
  EasyPasswords:
    - "123456"
  #未登录允许使用的命令
  AllowUsedComamnds:
    - "/l"
    - "/login"
    - "/reg"
    - "/register"

#禁用命令设置
BanCommandSettings:
  #开关
  Enable: true
  #OP免疫
  OpBypass: false
  #禁用命令列表
  BanCommandList:
    - plugins
    - bukkit:plugins
    - pl
    - bukkit:pl
    - ver
    - version
    - bukkit:ver
    - bukkit:version
  #使用被禁用的命令提示
  UsedBanCommandMessage:
  - "&c这个命令不存在,请重试!"

#超级Stop命令
SuperStopSettings:
  #开关
  Enable: true
  #服务器名称
  ServerName: "&6&l橙式插件-橙工具"
  #默认关服提示
  DefaultStopMessage: "%ServerName%\n&c&l服务器已关闭"

#聊天功能设置
ChatSettings:
  #聊天间隔限制开关
  ChatDelayEnable: false
  #聊天间隔限制
  ChatDelay: 3
  #聊天自定义格式开关
  ChatFormatEnable: true
  #聊天自定义格式
  ChatFormat: "&a%Player% &7>&f"
  #聊天屏蔽词开关
  ChatBlackWorkEnable: true
  #聊天屏蔽词
  ChatBlackWork:
    - SB
    - 傻逼